name: "Code CI"

on:
  # run on pushes to main
  push:
    branches:
      - main
      - gh-readonly-queue/main/**
    paths:
      - "src/**/*.txt"
  # run on pull requests that target the main branch
  pull_request:
    branches:
      - main
    paths:
      - "src/**/*.txt"
  # run weekly on Monday at 12:00
  schedule:
    - cron: '0 12 * * 1'
  workflow_dispatch:

concurrency:
  # on main, we want all builds to complete even if commits/merging happens faster to make it easier to discover at which point
  # something broke; else, we cancel "old" builds and run/(re)start the build with the latest changes
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}-{1}', github.workflow, github.sha) || format('ci-{0}-{1}', github.workflow, github.ref) }}

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: '.'

    permissions:
      contents: read

    env:
      # disabled-for-now renovate: datasource=github-releases depName=oven-sh/bun
      BUN_VERSION: 1.0.2

    steps:
      - name: Git - Checkout
        id: git_checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Bun - Setup
        id: bun_setup
        uses: oven-sh/setup-bun@8f24390df009a496891208e5e36b8a1de1f45135 # v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Bun - Install Dependencies
        id: bun_install
        # TODO: when renovate supports bun
        # run: bun install --frozen-lockfile
        run: bun install

      - name: Bun - Lint Filters
        id: bun_run_lint
        run: bun run lint

