name: "Code CI"

on:
  # run on pushes to main
  push:
    branches:
      - main
      - gh-readonly-queue/main/**
    paths:
      - "src/**/*.txt"
  # run on pull requests that target the main branch
  pull_request:
    branches:
      - main
    paths:
      - "src/**/*.txt"
  # run weekly on Monday at 12:00
  schedule:
    - cron: '0 12 * * 1'
  workflow_dispatch:

concurrency:
  # on main, we want all builds to complete even if commits/merging happens faster to make it easier to discover at which point
  # something broke; else, we cancel "old" builds and run/(re)start the build with the latest changes
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}-{1}', github.workflow, github.sha) || format('ci-{0}-{1}', github.workflow, github.ref) }}

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: '.'

    permissions:
      contents: read

    env:
      # disabled-for-now renovate: datasource=github-releases depName=oven-sh/bun
      BUN_VERSION: 1.1.10

    steps:
      - name: StepSecurity - Harden Github-hosted Runners
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit
          disable-telemetry: true
          disable-sudo: true

      - name: Git - Checkout
        id: git_checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Bun - Setup
        id: bun_setup
        uses: oven-sh/setup-bun@a1800f471a0bc25cddac36bb13e6f436ddf341d7 # v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Bun - Install Dependencies
        id: bun_install
        # TODO: when renovate supports bun
        # run: bun install --frozen-lockfile
        run: bun install

      - name: Bun - Lint Filters
        id: bun_run_lint
        run: bun run lint

  publish:
    name: 'Publish'
    runs-on: ubuntu-latest

    needs: [lint]

    defaults:
      run:
        shell: bash
        working-directory: '.'

    permissions:
      contents: read
      deployments: write

    steps:
      - name: StepSecurity - Harden Github-hosted Runners
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit
          disable-telemetry: true
          disable-sudo: true

      - name: Git - Checkout
        id: git_checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: YOUR_ACCOUNT_ID
          projectName: adblock-lists
          directory: ./src
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
